name: Context Testing
on:
  push:
    branches: [develop]

jobs:
  context-testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14.x, 16.x]
    steps:
      - name: Checkout to branch
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Check version of node
        run: npm --version
      - name: Dump GitHub Context
        id: github-context
        run: echo '${{ toJSON(github) }}'
      - name: Dump Job Context
        id: job-context
        run: echo '${{ toJSON(job) }}'
      - name: Dump Steps Context
        id: steps-context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump Runner Context
        id: runner-context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump Strategy Context
        id: strategy-context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump Matrix Context
        id: matrix-context
        run: echo '${{ toJSON(matrix) }}'
      - name: Dump Secrets Context
        id: secrets-context
        run: echo '${{ toJSON(secrets) }}'
